services:

  webscraper:
    build:
      context: .
      dockerfile: src/mcf_rag_chatbot/webscraper/Dockerfile
    volumes:
      - ./data:/app/data

  backend:
    build:
      context: .
      dockerfile: src/mcf_rag_chatbot/backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    depends_on:
      - webscraper
    environment:
    - GOOGLE_API_KEY=${GOOGLE_API_KEY}


  frontend:
    build:
      context: .
      dockerfile: src/mcf_rag_chatbot/frontend/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000
